config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'prototypes#index'
  resources :tags, only: [:index, :show]
  resources :user, only: [:show, :edit, :update]
  resources :prototypes, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: :create
    collection do
      get 'newest'
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :prototype, counter_cache: true
  belongs_to :user

end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  belongs_to :user
  has_many :likes
  has_many :comments, dependent: :destroy
  has_many :thumbnails, dependent: :destroy
  has_many :tags, dependent: :destroy

  accepts_nested_attributes_for :thumbnails

  validates_presence_of :title, :catch_copy, :concept

  acts_as_taggable

  acts_as_ordered_taggable_on :prototypes

  paginates_per 20

  def main_thumbnail
    thumbnails.main.first.name
  end

  def first_thumbnail
    thumbnails.sub.first.name
  end

  def second_thumbnail
    thumbnails.sub.second.name
  end

  def third_thumbnail
    thumbnails.sub.third.name
  end

  def main_thumbnails
    thumbnails.main
  end

  def sub_thumbnails
    thumbnails.sub
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :prototype
  belongs_to :user
end

app/models/thumbnail.rb
class Thumbnail < ActiveRecord::Base
  belongs_to :prototype

  mount_uploader :name, ImageUploader

  # validates_presence_of :name

  enum status: [:main, :sub]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true

  mount_uploader :avatar, ImageUploader

  has_many :prototypes
  has_many :likes
  has_many :comments
  has_many :tags

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:username, :avatar, :member, :profile, :works)
  end


  def after_sign_out_path_for(resource)
    user_session_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = current_user.comments.create(create_params)
    @comments = Comment.where(prototype_id: params[:prototype_id]).order('created_at ASC')
  end

  private
  def create_params
    prototype = params[:prototype_id]
    params.require(:comment).permit(:text).merge(prototype_id: prototype)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    like = current_user.likes.create(prototype_id: params[:prototype_id])
    likes_set
  end

  def destroy
    like = Like.find(params[:id])
    like.destroy
    likes_set
  end

  private
  def likes_set
    @prototype = Prototype.find(params[:prototype_id])
    @like = Like.find_by(user_id: current_user.id, prototype_id: params[:prototype_id])
    @likes = Like.where(prototype_id: params[:prototype_id])
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController

  before_action :set_prototype, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def index
    @prototypes = Prototype.includes(:thumbnails).order('likes_count DESC').page(params[:page])
  end

  def newest
    @prototypes = Prototype.includes(:thumbnails).order('created_at DESC').page(params[:page])
  end

  def show
    @prototype = Prototype.includes(:thumbnails).find(params[:id])
    @like = Like.find_by(user_id: @prototype.user_id, prototype_id: params[:id])
    @likes = Like.where(prototype_id: params[:id])
    @comment = Comment.new
    @comments = Comment.where(prototype_id: params[:id]).order('created_at ASC')
  end

  def new
    @prototype = Prototype.new
    @prototype.thumbnails.build
  end

  def create
    @prototype = current_user.prototypes.new(create_params)
    if @prototype.save
      redirect_to :root and return
    else
      render action: :new
    end
  end

  def edit
    unless @prototype.user_id == current_user.id
      redirect_to :root
    end
  end

  def update
    @prototype.update(update_params)
    redirect_to :root
  end

  def destroy
    @prototype.destroy
    redirect_to :root
  end

  private
  def create_params
    params.require(:prototype).permit(:title, :catch_copy, :concept, thumbnails_attributes: [:name, :status]).merge(tag_list: params[:prototype][:tag])
  end

  def update_params
    params.require(:prototype).permit(:title, :catch_copy, :concept, thumbnails_attributes: [:id, :name, :status]).merge(tag_list: params[:prototype][:tag])
  end

  def set_prototype
    @prototype = Prototype.find(params[:id])
  end
end

app/controllers/ranking_controller.rb
class RankingController < ApplicationController

  def index
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.most_used
  end

  def show
    @tag = ActsAsTaggableOn::Tag.most_used.find_by(id: params[:id])
    @tags = Prototype.tagged_with(@tag.name)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!, only: :edit
  def show
    @user = User.includes(:prototypes).find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to :root
    end
  end

  def update
    current_user.update(update_params)
    redirect_to controller: :prototypes, action: :index
  end

  private
  def update_params
    params.require(:user).permit(:username, :email, :member, :profile, :works, :avatar)
  end

end

app/views/comments/_comment.html.haml
.media
  .media-left
    = link_to image_tag("#{comment.user.avatar}", class: "media-object", alt: "64x64", data: {holder: {rendered: true}}, data: {src: "holder.js/64x64"}, style: "width: 64px; height: 64px;"), user_path(comment.user)
  .media-body
    %h4#top-aligned-media.media-heading
      = link_to comment.user.username, user_path(comment.user)
    %p
      = comment.text

app/views/comments/create.js.erb
$("#comment_text").val("");
$("span.num").html('(<%= @comments.count %>)');
$("#comment-link").html('<%= j(render partial: "comments/comment", collection: @comments) %>');

app/views/layouts/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px"), '/', class: "navbar-brand"
    .navbar-collapse.collapse.navbar-responsive-collapse
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            %a.dropdown-toggle{aria: {expanded: "false"}, data: {toggle:"dropdown"}, href: "#", role: "button" }
              = current_user.username
              %span.caret
            %ul.dropdown-menu{role: "menu"}
              %li
                = link_to 'My Page', user_path(current_user)
              %li
                = link_to 'Profile Edit', edit_user_path(current_user)
              %li
                = link_to 'Logout', destroy_user_session_path, method: :delete
          %li
            .btn.btn-primary.navbar-btn
              = link_to 'New Proto', new_prototype_path
      - else
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              = link_to 'Get Started', new_user_session_path
              

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", http: {equiv: "Content-Type"}}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', data: {turbolinks: {track: true}}
    %script{src: "http://code.jquery.com/jquery-1.10.2.js"}
    = javascript_include_tag 'application', data: {turbolinks: {track: true}}
    = csrf_meta_tags
  %body
    = render "layouts/header"
    = yield
    = render "layouts/footer"

app/views/likes/_like.html.haml
- if user_signed_in?
  - if @like.present?
    = link_to prototype_like_path(@prototype, @like), method: :delete, remote: true do
      %button.btn.btn-default
        =image_tag("icon_heart.svg")
        Like
        %span.num
          = @likes.count
  - else
    = link_to prototype_likes_path(@prototype), method: :post, remote: true do
      %button.btn.btn-default
        =image_tag("icon_heart.svg")
        Like
        %span.num
          = @likes.count
- else
  = link_to new_user_session_path do
    %button.btn.btn-default
      =image_tag("icon_heart.svg")
      Like
      %span.num
        = @likes.count

app/views/likes/create.js.erb
$("#like-link").html('<%= j(render partial: "likes/like") %>');

app/views/likes/destroy.js.erb
$("#like-link").html('<%= j(render partial: "likes/like") %>');

app/views/prototypes/_prototype.html.haml
.col-sm-4.col-md-3.proto-content.eachbox
  - if user_signed_in?
    - if prototype.user_id == current_user.id
      .dropdown.drop_menu_location
        = button_tag "ACTION", class: "btn btn-default dropdown-toggle", data: {toggle: "dropdown"}, id: "dropdownMenu", aria: {expanded: "false"}, type: "button", name: nil
        %ul.dropdown-menu{aria: {labelledby: "dropdownMenu1"}}
          %li
            = link_to "Delete", "/prototypes/#{prototype.id}", method: :delete, rel: "nofollow", data: {method: "delete"}
          %li
            = link_to "Edit", edit_prototype_path(prototype)
  .thumbnail
    = link_to image_tag(prototype.main_thumbnail), prototype_path(prototype)
    .caption
      %h3= prototype.title
      .proto-meta
        .proto-user
          = link_to "by #{prototype.user.username}", user_path(prototype.user_id)
        .proto-posted
          = prototype.created_at.strftime('%b %d')
      %ul.proto-tag-list.list-inline
        - prototype.tags.each do |tag|
          %li 
            = link_to "#{tag.name}", tag_path(tag), class: "btn btn-default"

app/views/prototypes/edit.html.haml
.container.proto-new
  = form_for @prototype do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          = f.text_field :title, placeholder: "Title", type: "text", class: "proto-new-title"
      .row
        .col-md-12
          .cover-image-upload
            = f.fields_for :thumbnails, @prototype.main_thumbnails do |t|
              = t.file_field :name
              = t.hidden_field :status, value: :main
        .col-md-12
          %ul.proto-sub-list.list-group
            - 2.times do
              = f.fields_for :thumbnails, @prototype.sub_thumbnails do |t|
                %li.list-group-item.col-md-4
                  .image-upload
                    = t.file_field :name
                    = t.hidden_field :status, value: :sub

            = f.fields_for :thumbnails do |t|
              %li.list-group-item.col-md-4#hide-form
                .image-upload
                  = t.file_field :name
                  = t.hidden_field :status, value: :sub
            %li.list-group-item.col-md-4#show-form
              .image-upload-plus
                %span +
      .row.proto-description
        = f.text_field :catch_copy, placeholder: "Catch Copy", type: "text", class: "col-md-12"
        = f.text_area :concept, placeholder: "Concept", cols: "30", rows: "4", class: "col-md-12"
        .col-md-12
          %h4 Tag List
          .row
            .col-md-3
              =text_field_tag "prototype[tag][]", "", placeholder: "Web Design"
            .col-md-3
              =text_field_tag "prototype[tag][]", "", placeholder: "UI"
            .col-md-3
              =text_field_tag "prototype[tag][]", "", placeholder: "Application"

      .row.text-center.proto-btn
        = f.submit "Publish", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")
.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{role: "presentation"}
          = link_to "Popular PROTO", root_path
        %li{role: "presentation"}
          = link_to "Newest PROTO", newest_prototypes_path
      = link_to "View Tags", tags_path, class: "btn btn-default col-lg-1", type: "button", name: "button"
.container.proto-list
  .row
    = render partial: "prototype", collection: @prototypes
.text-center
  = paginate(@prototypes)

app/views/prototypes/new.html.haml
.container.proto-new
  = form_for @prototype do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          = f.text_field :title, placeholder: "Title", type: "text", class: "proto-new-title", required: true
      .row
        .col-md-12
          .cover-image-upload
            = f.fields_for :thumbnails do |t|
              = t.file_field :name, id: "main-file"
              %img{src: "", id: "main-preview", style: "display:none;"}
              = t.hidden_field :status, value: :main
        .col-md-12
          %ul.proto-sub-list.list-group
            - i = 0
            - 2.times do
              = f.fields_for :thumbnails do |t|
                %li.list-group-item.col-md-4
                  .image-upload
                    = t.file_field :name, id: "sub-file#{i}"
                    %img{src: "", id: "sub-preview#{i}", style: "display:none;"}
                    = t.hidden_field :status, value: :sub
                    - i = i + 1
            = f.fields_for :thumbnails do |t|
              %li.list-group-item.col-md-4#hide-form
                .image-upload
                  = t.file_field :name, id: "sub-file2"
                  %img{src: "", id: "sub-preview2", style: "display:none;"}
                  = t.hidden_field :status, value: :sub
            %li.list-group-item.col-md-4#show-form
              .image-upload-plus
                %span +
      .row.proto-description
        = f.text_field :catch_copy, placeholder: "Catch Copy", type: "text", class: "col-md-12", required: true
        = f.text_area :concept, placeholder: "Concept", cols: "30", rows: "4", class: "col-md-12", required: true
        .col-md-12
          %h4 Tag List
          .row
            .col-md-3
              =text_field_tag "prototype[tag][]", "", placeholder: "Web Design"
            .col-md-3
              =text_field_tag "prototype[tag][]", "", placeholder: "UI"
            .col-md-3
              =text_field_tag "prototype[tag][]", "", placeholder: "Application"

      .row.text-center.proto-btn
        = f.submit "Publish", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/newest.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")
.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li{role: "presentation"}
          = link_to "Popular PROTO", root_path
        %li.active{role: "presentation"}
          = link_to "Newest PROTO", newest_prototypes_path
      = link_to "View Tags", tags_path, class: "btn btn-default col-lg-1", type: "button", name: "button"
.container.proto-list
  .row
    = render partial: "prototype", collection: @prototypes
.text-center
  = paginate(@prototypes)

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to image_tag("#{@prototype.user.avatar}", class: "media-object", alt: "64x64", data: {holder: {rendered: true}}, data: {src: "holder.js/64x64"}, style: "width: 64px; height: 64px;"), user_path(@prototype.user)
        .media-body
          %h4#top-aligned-media.media-heading
            = @prototype.title
          .proto-user
            = link_to "by #{@prototype.user.username}", user_path(@prototype.user_id)
            %span.degree= "#{@prototype.user.profile} #{@prototype.user.works}"
    .col-md-6.text-right{id: "like-link"}
      = render partial: "likes/like"
  .row
    .col-md-9
      = image_tag(@prototype.main_thumbnail, class: "img-responsive")
    - if @prototype.first_thumbnail.present?
      .col-md-3
        %ul.proto-sub-list.list-group
          %li.list-group-item
            = image_tag(@prototype.first_thumbnail, class: "img-responsive")
          - if @prototype.second_thumbnail.present?
            %li.list-group-item
              = image_tag(@prototype.second_thumbnail, class: 'img-responsive')
          - if @prototype.third_thumbnail.present?
            %li.list-group-item
              = image_tag(@prototype.third_thumbnail, class: 'img-responsive')
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p= @prototype.catch_copy
    .col-md-6
      %h4 Concept
      %p= @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        - @prototype.tags.each do |tag|
          %li 
            = link_to "#{tag.name}", tag_path(tag), class: "btn btn-default"
  .row.proto-comments
    %h4.col-md-12
      Comments
      %span.num (#{@comments.count})
    .col-md-8
      #comment-link
        = render partial: "comments/comment", collection: @comments
      - if user_signed_in?
        .form-inline{role: "form"}
          = form_for [@prototype, @comment], remote: true do |f|
            %h4 Write a comment
            .row
              .form-group.col-md-10
                = f.text_area :text, placeholder: "Your comments", rows: "3", class: "form-control", required: true
              .form-group.col-md-2
                = f.submit "Comment", class: "btn btn-primary"
      - else
        .form-inline{role: "form"}
          %h4 Write a comment
          .row
            .form-group.col-md-10
              %textarea{placeholder: "Your comments", rows: "3", class: "form-control"}
            .form-group.col-md-2
              = link_to "Comment", new_user_session_path, class: "btn btn-primary"

app/views/tags/_each_tag.html.haml
.col-sm-4.col-md-3.proto-content.eachbox
  - if user_signed_in?
    - if each_tag.user_id == current_user.id
      .dropdown.drop_menu_location
        = button_tag "ACTION", class: "btn btn-default dropdown-toggle", data: {toggle: "dropdown"}, id: "dropdownMenu", aria: {expanded: "false"}, type: "button", name: nil
        %ul.dropdown-menu{aria: {labelledby: "dropdownMenu1"}}
          %li
            = link_to "Delete", "/prototypes/#{each_tag.id}", method: :delete, rel: "nofollow", data: {method: "delete"}
          %li
            = link_to "Edit", edit_prototype_path(each_tag)
  .thumbnail
    = link_to image_tag(each_tag.main_thumbnail), prototype_path(each_tag)
    .caption
      %h3= each_tag.title
      .proto-meta
        .proto-user
          = link_to "by #{each_tag.user.username}", user_path(each_tag.user_id)
        .proto-posted
          = each_tag.created_at.strftime('%b %d')
      %ul.proto-tag-list.list-inline
        - each_tag.tags.each do |tag|
          %li 
            = link_to "#{tag.name}", tag_path(tag), class: "btn btn-default"

app/views/tags/_tag.html.haml
%li.col-md-4
  = link_to tag.name, tag_path(tag), class: "btn btn-default"

app/views/tags/index.html.haml
.container
  .row
    .tags-list
      %h2 Tags list
      %ul
        = render partial: 'tag', collection: @tags
  

app/views/tags/show.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")
.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{role: "presentation"}
          = link_to "Popular PROTO", "#"
        %li{role: "presentation"}
          = link_to "Newest PROTO", "#"
      = link_to "View Tags", tags_path, class: "btn btn-default col-lg-1", type: "button", name: "button"
.container.proto-list
  .row
    = render partial: "each_tag", collection: @tags

app/views/user/_prototype.html.haml
.col-sm-4.col-md-3.proto-content.eachbox
  - if user_signed_in?
    - if prototype.user_id == current_user.id
      .dropdown.drop_menu_location
        = button_tag "ACTION", class: "btn btn-default dropdown-toggle", data: {toggle: "dropdown"}, id: "dropdownMenu", aria: {expanded: "false"}, type: "button", name: nil
        %ul.dropdown-menu{aria: {labelledby: "dropdownMenu1"}}
          %li
            = link_to "Delete", "/prototypes/#{prototype.id}", method: :delete, rel: "nofollow", data: {method: "delete"}
          %li
            = link_to "Edit", edit_prototype_path(prototype)
  .thumbnail
    = link_to image_tag(prototype.main_thumbnail), prototype_path(prototype)
    .caption
      %h3= prototype.title
      .proto-meta
        .proto-date
          = prototype.created_at.strftime('%b %d')
      %ul.proto-tag-list.list-inline
        - prototype.tags.each do |tag|
          %li 
            = link_to "#{tag.name}", tag_path(tag), class: "btn btn-default"

app/views/user/edit.html.haml
.container.user-new
  = form_for current_user do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h2 Edit Profile
          .user-name_image.row
            .user-name.col-md-10
              = f.text_field :username, placeholder: "Username"
            .user-image.col-md-2{style: 'background-image: url();'}
              = button_tag "Change image", class: "btn btn-primary"
              = f.file_field :avatar, type: "file", id: "avatar"
              %img{src: "", id: "avatar-preview", style: "display:none;"}
          = f.email_field :email, class: "user-email", placeholder: "E-Mail"
          = f.password_field :password, class: "user-password", placeholder: "Password"
        .col-md-12
          %h4 Member of
          .user-user-member.row
            .user-name.col-md-12
              = f.text_field :member, placeholder: "Member"
          %h4 Profile
          .user-user-profile.row
            .user-name.col-md-12
              = f.text_area :profile, placeholder: "Profile", cols: "30", rows: "4"
          %h4 Works
          .user-name_image.row
            .user-name.col-md-12
              = f.text_area :works, placeholder: "Works", cols: "30", rows: "4"
      .row.text-center.user-btn
        = f.submit "Save", class: "btn btn-lg btn-primary btn-block"

app/views/user/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        = link_to image_tag("#{@user.avatar}", class: "media-object", alt: "64x64", data: {holder: {rendered: true}}, data: {src: "holder.js/64x64"}, style: "width: 64px; height: 64px;"), user_path(@user)
      .media-body
        %h4#top-aligned-media.media-heading
          = @user.username
          %span.label.label-default.project-number
            = @user.prototypes.count
            %i Projects
        .proto-user
          %span.degree= @user.member
        .row
          .col-md-6
            %h4 Profile
            %p= @user.profile
          .col-md-6
            %h4 Works
            %p= @user.works
.container.proto-list
  .row
    = render partial: "prototype", collection: @user.prototypes